# Generated by Django 5.0.6 on 2024-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="react",
            name="department",
        ),
        migrations.RemoveField(
            model_name="react",
            name="employee",
        ),
        migrations.AddField(
            model_name="react",
            name="benefits",
            field=models.CharField(default="default value", max_length=100),
        ),
        migrations.AddField(
            model_name="react",
            name="contact",
            field=models.CharField(default="default value", max_length=100),
        ),
        migrations.AddField(
            model_name="react",
            name="description",
            field=models.CharField(default="default value", max_length=100),
        ),
        migrations.AddField(
            model_name="react",
            name="intro",
            field=models.CharField(default="default value", max_length=100),
        ),
        migrations.AddField(
            model_name="react",
            name="lcoation",
            field=models.CharField(default="default value", max_length=100),
        ),
        migrations.AddField(
            model_name="react",
            name="title",
            field=models.CharField(default="default value", max_length=100),
        ),
    ]
