# Generated by Django 5.0.6 on 2024-06-02 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_react_department_remove_react_employee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="react",
            old_name="lcoation",
            new_name="location",
        ),
    ]
